### ISSUE TITLE
Trivial __init__.py error for Python 3

### ISSUE THREAD

**Issue by zunzun** [lgastako/db#3]
Line 69 in __init__.py reads

print "var", var

which fails in Python 3.  A simple fix is:

try:
    print "var", var   # Python 2
except:
    print("var", var)   # Python 3

**Comment by theSabza** [comment]
also python3 does not has urlparser, do the following in __init__ & drivers.py file 

`pip install urllib3 -> this is with pip3`

go to files and add following lines 
`from urllib import parse as urlparse`
instead of 
`import urlparser`

**Comment by zunzun** [comment]
My code does not have a drivers.py file.
